// Project Zero Chapter 1: Ravenhado - English story data
(function(global){
  "use strict";
  global.PZ_CHAPTER1_STAGES_EN = [
    {name:"Temporary Squad",desc:"Hermit joins Nox's squad temporarily and receives the Project 4 investigation assignment."},
    {name:"Northern Blockade",desc:"The squad clears the road leading toward Project 4."},
    {name:"Abandoned for Six Years",desc:"Clear immediate threats and inspect three abnormal crystal readings."},
    {name:"A Cry in the Ruins",desc:"Trace the distress call, break the encirclement, and reach Xiaolai."},
    {name:"Shadow Overhead",desc:"A dragon crosses the sky and forces the squad to change plans."},
    {name:"Rooftop Withdrawal",desc:"Escort Xiaolai across three routes and secure each withdrawal marker."},
    {name:"Beneath the Rift",desc:"Lai falls into a mysterious rift, and the squad follows her."},
    {name:"Six Years of Survivors",desc:"Survey residents, supplies, and the unstable rift exit without combat."},
    {name:"Crystalized Raiders",desc:"Defend the settlement and its remaining supplies from crystalized raiders."},
    {name:"The Rescue Begins",desc:"The squad returns to Ravenhado to request government support."}
  ];
  global.PZ_CHAPTER1_STORY_EN = {
    1:[["Narrator","An investigation file from the northern district rests on a table in the Ravenhado Affairs Office."],["Nox","Project 4. Abandoned for six years. We investigate the anomaly and clear any immediate threat."],["{playerName}","Project 4?"],["Ailo","You just arrived, so it makes sense that you haven't heard about it."],["Kane","You're joining our squad temporarily. Follow Nox's orders and don't move alone."],["Flora","Crystal density in the north is unstable. Stay within sight of the team."],["Nox","Kane, Ailo, Flora, Hermit, and me. Move out."],["System","Chapter 1: Forgotten Project 4 begins."]],
    2:[["Narrator","The squad reaches the silent streets beyond the northern blockade."],["Ailo","It looks worse than the archive photos."],["Kane","Crystal beasts ahead. Clear a route we can also use to withdraw."],["Nox","Hold formation. Hermit takes the center."],["System","Objective: break through the blockade and reach Project 4."]],
    3:[["Narrator","The rusted PROJECT 4 sign is still visible above the road."],["{playerName}","No one came back in six years?"],["Kane","Teams reached the perimeter, but the internal structure kept changing."],["Flora","These crystal readings do not look natural."],["Nox","Record the coordinates. We continue."],["System","Objective: clear threats and press F at all three anomaly readings."]],
    4:[["Narrator","A cry for help echoes from the ruined commercial district."],["Lai","Over here! Help!"],["Ailo","Someone is surrounded!"],["Nox","Kane opens the route. Hermit follows. Flora, prepare treatment."],["System","Objective: break the encirclement and press F at Xiaolai's rescue point."]],
    5:[["Narrator","After the last beast falls, the rescued girl leans against a broken wall."],["Kane","Name. Why are you here?"],["Lai","I'm Lai. I came up from below to find supplies."],["Nox","Below? The underground sector has been sealed for six years."],["Narrator","Before Lai can answer, the sky darkens."],["Narrator","A massive dragon passes over the district, covering the streets in shadow."],["Flora","That crystal response resembles what appeared in the Daydream."],["Ailo","More enemies are approaching."],["Nox","End the investigation. Escort Lai to the rooftops!"]],
    6:[["Narrator","The squad escorts Lai through narrow streets as crystal beasts close in."],["Lai","My leg is too slow. Leave me."],["Kane","No. We don't throw someone back after saving them."],["Ailo","The building ahead still reaches the roof."],["Nox","Hermit covers the rear. Everyone move."],["System","Objective: secure three withdrawal routes and confirm each marker with F."]],
    7:[["Narrator","The squad reaches the rooftop. The dragon has vanished behind the clouds."],["Lai","Wait... something is below us."],["Narrator","Loose debris gives way beneath Lai, and she falls from the ledge."],["{playerName}","Grab my hand!"],["Narrator","Hermit reaches for her but misses."],["Flora","A rift opened below. She didn't reach the ground!"],["{playerName}","She's alive. I'm going after her."],["Kane","The squad moves together. Enter on my count."]],
    8:[["Narrator","There is no sky inside the rift. Dim light leaks through rock and abandoned structures."],["Ailo","People have been living here."],["Resident","Don't attack! We aren't raiders!"],["Narrator","Weak residents emerge from improvised shelters. Their supplies are nearly gone."],["Lai","I'm safe. They found me."],["Resident","We've been trapped here for six years. People passed outside, but no one ever found us."],["Flora","Many need food and treatment."],["Nox","Why can't you leave through the rift?"],["Resident","It opens rarely, and never in the same direction."],["{playerName}","Then we'll find a way out for everyone."]],
    9:[["Narrator","An alarm rises from the edge of the settlement."],["Resident","The crystalized raiders are back! They're after the food!"],["Kane","Late-stage infected. They can still plan and organize."],["Flora","They aren't mindless monsters, but we cannot let the settlement lose its supplies."],["Nox","Drive them back. Do not pursue. Hermit, hold the front with me."],["System","Objective: defend the settlement and repel the raiders."]],
    10:[["Narrator","The attackers retreat deeper into the rift."],["Lai","Thank you... but they'll return."],["Nox","This place cannot be defended forever. They need supplies, medicine, and a stable exit."],["Flora","I can leave basic medicine, but it won't last long."],["Kane","We return to Ravenhado and deliver the coordinates to the government."],["Ailo","Project 4 cannot be treated as an empty ruin again."],["{playerName}","Six years was already too long. We'll come back."],["Narrator","The squad leaves the rift. The real rescue operation is about to begin."],["System","Chapter 1: Forgotten Project 4 complete."]]
  };
})(window);
