// Project Zero Chapter 2: Ravenhado - English story data
(function(global){
  "use strict";
  global.PZ_CHAPTER2_STAGES_EN = [
    {name:"A Rescue Denied",desc:"The government's response orders the squad to stop intervening in Project 4."},
    {name:"Silence and Choice",desc:"Between orders and lives, the five must decide whether to return."},
    {name:"Across the Security Line",desc:"Avoid patrols and inspect three blind spots to enter Project 4 without combat."},
    {name:"The Closing Rift",desc:"Clear each anchor and stabilize the shrinking rift entrance."},
    {name:"Stay or Leave",desc:"Hear the residents and record who will evacuate, remain, or hesitate."},
    {name:"The Final Window",desc:"Escort the survivors through three collapsing outer passages."},
    {name:"One Person Missing",desc:"Investigate Lai's last known position and the traces she left behind."},
    {name:"The Fox Spirit's Guidance",desc:"Defend three resonance points while Flora's fox spirit locates the exit."},
    {name:"The Weeping Dragon",desc:"Hermit enters the Daydream again and encounters a dragon and an unknown woman."},
    {name:"Run for the Exit",desc:"Repel the pursuit and lead the survivors through the final opening."},
    {name:"Beyond the Exit",desc:"The survivors escape, only to meet a government containment team."}
  ];
  global.PZ_CHAPTER2_STORY_EN = {
    1:[["Narrator","The Project 4 rescue report is pushed back across a government desk."],["Official","Project 4 is a high-risk zone. Unauthorized action may obstruct the investigation and cause more casualties."],["Ailo","Those people have already waited six years."],["Official","The relevant department will handle the survivors. Stop intervening."],["Kane","And if they cannot wait that long?"],["Official","The order stands."],["System","The rescue request is denied."]],
    2:[["Narrator","The five stop in an empty corridor after leaving the hearing."],["Ailo","Waiting means starvation, worsening crystal sickness, or another raid."],["Nox","As captain, I cannot ignore the order—or everyone's safety."],["Flora","Doing nothing would extend the silence that hid them for six years."],["Kane","I'm going back. I refuse to arrive too late again."],["{playerName}","I'm going too."],["Narrator","After a long silence, Nox puts away the government communicator."],["Nox","Avoid patrols. No confrontation. We return together."],["System","Chapter 2: Choice begins."]],
    3:[["Narrator","Night covers the northern district as the squad approaches through an abandoned maintenance route."],["Ailo","Three monitoring groups ahead. Their patrol routes overlap at regular intervals."],["Nox","Inspect the old beacons and move through the blind spots."],["Kane","We're here to save people, not fight our own side."],["System","Objective: inspect three security blind spots without combat."]],
    4:[["Narrator","The rift has narrowed into an unstable band of light."],["Flora","It is healing. Stabilize the remaining anchors before it closes."],["Nox","Clear each anchor, then press F to calibrate it."],["{playerName}","No time to hesitate."],["System","Objective: stabilize all three rift anchors."]],
    5:[["Narrator","The settlement is quieter than before. Residents gather around its last lights."],["Nox","The government will not act immediately. We can only take those willing to leave."],["Resident","This is the only home I remember. I will stay."],["Resident","Will the outside world accept us?"],["Lai","I want to leave, but I don't want to abandon anyone."],["Flora","The choice is theirs. We must hear every answer."],["System","Objective: record the residents' evacuation choices in all three areas."]],
    6:[["Narrator","The residents who chose to leave enter the outer passage with only essential belongings."],["Kane","Keep moving. Those who need help stay in the center."],["Ailo","The rear passage is collapsing, and the noise is drawing crystal beasts."],["Nox","Hermit opens the route. Confirm everyone passes each marker."],["System","Objective: escort the survivors through three passages."]],
    7:[["Narrator","Nox counts the group as they reach the outer rift layer."],["Nox","One missing. Lai isn't here."],["{playerName}","I'm going back."],["Nox","The entrance is gone. Find her direction first, or more people will be trapped."],["Flora","The fox spirit can sense her, but overlapping space is distorting the trail."],["System","Objective: inspect Lai's last position, belongings, and rift echo."]],
    8:[["Narrator","The fox spirit stops before a wall where no path exists."],["Flora","It found the exit, but three resonance points must remain stable."],["Nox","Flora confirms the route. Everyone else holds the perimeter."],["Ailo","The pursuit caught up!"],["Kane","Then they come no closer."],["System","Objective: repel the pursuit and confirm all three resonance points."]],
    9:[["Narrator","The battle noise vanishes. Hermit opens their eyes in an unfamiliar silent world."],["{playerName}","Nox? Kane?"],["Narrator","A massive dragon stands in the distance, tears falling from its eyes."],["Narrator","As Hermit approaches, an unknown woman appears between them."],["Unknown Woman","You should not be here."],["Narrator","An unseen force drives Hermit back. The dragon roars and light fills everything."],["Narrator","Hermit wakes in reality, carried on Nox's back."],["Nox","Finally awake. Don't fall behind again."],["System","Daydream record: weeping dragon, unknown woman, unidentified space."]],
    10:[["Narrator","The path sensed by the fox spirit appears, but the exit is shrinking quickly."],["Flora","This is the final window. If we miss it, the direction disappears again."],["Nox","Kane holds the rear. Ailo protects the residents. Hermit moves with me."],["{playerName}","Everyone gets out together."],["System","Objective: complete three evacuation battles and reach the exit."]],
    11:[["Narrator","The final survivor crosses the light. The rift closes behind the group."],["Ailo","We made it... we really brought them out."],["Narrator","Freedom is not waiting outside. A stern man stands with a containment team."],["Government Lead","All survivors will undergo screening. Your squad will submit a complete action record."],["Kane","They just escaped. Let the medical team take over first."],["Government Lead","Medical staff are ready. Everything else comes later."],["Narrator","The survivors are escorted away. Lai is nowhere among them."],["Flora","The fox spirit still senses her. Faintly, but it has not vanished."],["{playerName}","Then this isn't over."],["System","Ravenhado Chapter 2: Choice complete. Daydream Reconstruction unlocked."]]
  };
})(window);
