// Project Zero V49.32.2 - main-story narrative expansion
(function(g){
  "use strict";
  function extend(story,stages,atmos,narrator,record){
    if(!story||!stages)return;
    stages.forEach((stage,i)=>{const scene=story[i+1];if(!Array.isArray(scene))return;const desc=stage.zhDesc||stage.desc||"";scene.splice(Math.max(1,scene.length-1),0,[narrator,atmos[i]||atmos[atmos.length-1]],[record,desc]);});
  }
  extend(g.PZ_CHAPTER0_STORY_ZH,g.PZ_CHAPTER0_STAGES_ZH,[
    "西区的警报灯在雨雾里一盏接一盏亮起，街面残留着尚未冷却的晶体碎屑。","撤离广播被干扰切成断句，远处的人群正沿临时标记向西门移动。","风声突然停止，飘落的尘埃悬在半空，世界像被某种力量按下暂停。","废墟没有任何熟悉的城市声响，只有倒塌楼体深处传来缓慢而规律的震动。","人形晶体的表面映出破碎街景，它的动作却越来越接近真正的战士。","同一条街道在两人的视野中呈现出完全不同的损毁状态。","边界外的光线被拉成长线，脚下道路随着呼吸般的脉冲反复改变。","侵蚀让距离感逐渐失真，近处的路牌看起来像隔着数公里。","巨型结晶每次脉动都会孵化新的轮廓，周围空间因此不断收紧。","结晶巨人的脚步令整片中层震动，核心光芒在裂纹之间快速游走。","现实的通讯声重新涌入耳中，但白日梦残留的低鸣仍未完全消失。"
  ],"旁白","行动记录");
  extend(g.PZ_CHAPTER0_STORY_EN,g.PZ_CHAPTER0_STAGES_EN,[
    "West District warning lights ignite one after another through the rain, illuminating crystal fragments that have not yet cooled.","Interference cuts the evacuation broadcast into fragments while civilians follow temporary markers toward the west gate.","The wind stops without warning. Dust hangs motionless in the air as if the world has been paused.","No familiar city noise remains in the ruins; only a slow, measured vibration rises from beneath the collapsed structures.","Broken streets reflect across the humanoid crystal's surface while its movements grow disturbingly close to those of a trained fighter.","The same street now shows two incompatible states of destruction to the two investigators.","Light stretches into narrow bands beyond the boundary, and the road shifts with each pulse beneath their feet.","Erosion twists their sense of distance until a nearby sign appears kilometers away.","Each pulse from the giant crystal forms another silhouette and tightens the surrounding space.","Every step of the colossus shakes the middle layer as core-light races through its fractures.","Reality's communications flood back, but the low resonance of the Daydream does not fully disappear."
  ],"Narrator","Operation Record");
  extend(g.PZ_CHAPTER1_STORY_ZH,g.PZ_CHAPTER1_STAGES_ZH,[
    "档案室的投影地图缺失了整整一个城区，Project 4 的位置只剩一块灰色空白。","北区封锁线外仍有遗弃车辆，车门敞开，座位上落满六年的尘土。","外环建筑保存着撤离当天的状态，日历、餐具与未关闭的终端像在等待主人回来。","求救声在空楼之间反复折返，无法仅凭方向判断真正来源。","巨影掠过时遮住整条街的光，晶体怪也在同一瞬间改变了行动方向。","撤离路线横跨三处不稳定街区，每一段安全标记都可能在几分钟后失效。","裂隙下方没有正常重力，碎石与旧物沿着看不见的轨道缓慢漂浮。","聚居地用废弃广告牌和车厢搭成房屋，六年的生活痕迹层层覆盖其上。","警报响起后，居民没有慌乱，而是熟练地把药品和孩子转移到最内侧。","裂隙出口再次闪烁，外界的灯光第一次完整照进这座被遗忘的聚居地。"
  ],"旁白","行动记录");
  extend(g.PZ_CHAPTER1_STORY_EN,g.PZ_CHAPTER1_STAGES_EN,[
    "An entire district is missing from the archive projection; Project 4 remains only as a gray void on the map.","Abandoned vehicles still line the North District blockade, their open doors and seats buried beneath six years of dust.","The outer buildings preserve evacuation day exactly—calendars, dishes, and terminals waiting for owners who never returned.","The distress call rebounds between empty towers, making its true direction impossible to judge by sound alone.","The passing shadow blocks all light from the street, and every crystal creature changes direction at once.","The evacuation route crosses three unstable blocks where a confirmed safety marker may become useless minutes later.","Normal gravity is absent below the rift; debris and personal belongings drift along invisible paths.","The settlement has turned old billboards and train cars into homes, layering six years of life over the ruins.","When the alarm sounds, residents move medicine and children inward with the practiced calm of long survival.","The rift exit flickers again, allowing outside light to reach the forgotten settlement in full for the first time."
  ],"Narrator","Operation Record");
  extend(g.PZ_CHAPTER2_STORY_ZH,g.PZ_CHAPTER2_STAGES_ZH,[
    "会议桌上的救援名单被盖上暂缓印章，名单末尾仍留着数个没有确认生死的名字。","命令要求所有人沉默，但每个人都记得聚居地里正在减少的药品。","夜间警戒灯按固定节奏扫过围墙，十一秒的盲区成为唯一入口。","裂隙边缘像伤口一样缓慢闭合，每次收缩都会抹去一段原有道路。","居民把选择写在旧车票背面，有人收拾行李，也有人守在已经住了六年的门口。","队伍把撤离者分成数组，最慢的一组始终听见身后传来空间碎裂声。","清点表连续核对三次仍少一个名字，小赖留下的位置只有一条偏离队伍的脚印。","狐灵在不同方向留下短暂光点，错误的光点很快被黑暗吞没。","巨龙的眼泪落下后化为透明晶体，神秘女子的身影隔着晶体注视主角。","出口光芒正在变窄，最后一组幸存者几乎是贴着崩塌边缘冲出去。","外界的空气重新变得真实，迎接众人的却不是庆祝，而是一整排封锁人员。"
  ],"旁白","行动记录");
  extend(g.PZ_CHAPTER2_STORY_EN,g.PZ_CHAPTER2_STAGES_EN,[
    "The rescue list receives a suspension stamp while several names at the bottom remain unconfirmed.","The order demands silence, but everyone remembers the settlement's dwindling medicine.","Night patrol lights sweep the wall in a fixed rhythm, leaving an eleven-second blind interval as the only entrance.","The rift closes like a healing wound, erasing another section of road with every contraction.","Residents write their decisions on old tickets; some pack while others remain at doors they have guarded for six years.","Evacuees are divided into groups, and the slowest group hears space fracture behind them throughout the crossing.","Three counts still leave one name missing. Only a set of footprints turning away from the group marks Lai's last position.","The fox spirit leaves brief lights in several directions, and every false light is quickly swallowed by darkness.","The dragon's tears become transparent crystals while the mysterious woman watches the protagonist through them.","The exit narrows to a blade of light as the final survivors run beside the collapsing edge.","The outside air feels real again, but a full containment unit—not celebration—waits beyond the exit."
  ],"Narrator","Operation Record");
  extend(g.PZ_CHAPTER3_PART1_STORY_ZH,g.PZ_CHAPTER3_PART1_STAGES_ZH,["会议室玻璃隔绝了广场的喧闹，却隔不住不断刷新的扩张警报。","雨中的广场挤满等待答案的人，每一块媒体屏幕都显示不同版本的伤亡数字。","主角穿过人群时没有告别，只把小赖留下的线索重新确认了一遍。","越过扩张边界后，城市的颜色迅速褪去，熟悉道路被新生晶体切断。","高楼坍塌卷起的尘雾尚未散去，裂隙内部已经传来新的回应。","重叠道路不断将主角送回原点，只有小赖留下的痕迹没有改变方向。","裂隙核心的空间正在收缩，怪物的包围圈也随之越来越近。","巨龙睁眼的瞬间，周围所有细小结晶同时朝它俯下。"],"旁白","行动记录");
  extend(g.PZ_CHAPTER3_PART1_STORY_EN,g.PZ_CHAPTER3_PART1_STAGES_EN,["The meeting-room glass blocks the plaza's noise but not the expansion alerts refreshing across every screen.","The rain-soaked plaza is packed with people awaiting answers while each media display reports a different casualty count.","The protagonist crosses the crowd without saying goodbye, checking Lai's final clues one more time.","Beyond the expansion boundary, color drains from the city and newborn crystal cuts through familiar roads.","Dust from the fallen tower still hangs in the air when a new response rises from inside the rift.","Overlapping streets repeatedly return the protagonist to the same place; only Lai's trail keeps its direction.","Space contracts around the rift core as the creatures' encirclement draws closer.","When the dragon opens its eyes, every smaller crystal bends toward it at once."],"Narrator","Operation Record");
  extend(g.PZ_CHAPTER3_PART2_STORY_ZH,g.PZ_CHAPTER3_PART2_STAGES_ZH,["晶体封锁从出口一路蔓延到高处，最后一条撤离路径在众人眼前消失。","克罗斯的每次振翼都会改变安全区域，破碎空间在战场边缘反复闭合。","列车驶离时，修复城市的灯光一盏盏接替远去的废墟。"],"旁白","行动记录");
  extend(g.PZ_CHAPTER3_PART2_STORY_EN,g.PZ_CHAPTER3_PART2_STAGES_EN,["Crystal spreads from the exit to the ceiling until the last evacuation path disappears.","Every beat of Kros's wings relocates the safe ground while fractured space closes and opens around the arena.","As the train departs, the lights of reconstruction replace the receding ruins one by one."],"Narrator","Operation Record");
})(window);
